/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dima' at '09/06/16 00:19' with Gradle 2.10
 *
 * @author dima, @date 09/06/16 00:19
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
