import org.junit.Test;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'dima' at '09/06/16 00:19' with Gradle 2.10
 *
 * @author dima, @date 09/06/16 00:19
 */
public class MainTest {

    @Test
    public void test() {
    }
}
